name: testing xvr programming lang

on: [push, pull_request]

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: find C source files
        run: find . -type f \( -name "*.c" -o -name "*.h" \) > c_files.txt
        
      - name: check formatting
        run: |
          while IFS= read - r file; do
            if ! clang-format --dry-run -Werror "$file"; then
              echo "not formatted: $file"
              exit 1
            fi
          done < c_files.txt
        shell: bash

      - name: testing
        run: make tests-cases
